#!/usr/bin/env bash
#
# dork installer.
#
#   curl -fsSL https://raw.githubusercontent.com/pipedreamerai/dork/main/install.sh | bash
#
# Clones (or updates) dork into $DORK_HOME (default ~/.dork) and writes a
# `dork` launcher into a writable bin dir on your PATH. Running ./install.sh
# from a checkout uses that checkout as DORK_HOME instead of cloning.
#
set -euo pipefail

REPO_URL="${DORK_REPO_URL:-https://github.com/pipedreamerai/dork.git}"

# Running from a checkout? Use it. Piped through bash? Clone.
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [[ -n "$SCRIPT_DIR" && -f "$SCRIPT_DIR/bin/dork" ]]; then
  DORK_HOME="$SCRIPT_DIR"
else
  DORK_HOME="${DORK_HOME:-$HOME/.dork}"
  if [[ -d "$DORK_HOME/.git" ]]; then
    echo "[dork] Updating existing install in $DORK_HOME"
    git -C "$DORK_HOME" pull --ff-only
  elif [[ -e "$DORK_HOME" ]]; then
    echo >&2 "[dork] $DORK_HOME exists but is not a dork checkout — remove it or set DORK_HOME elsewhere."
    exit 1
  else
    echo "[dork] Cloning $REPO_URL to $DORK_HOME"
    git clone --depth 1 "$REPO_URL" "$DORK_HOME"
  fi
fi

chmod +x "$DORK_HOME/bin/dork"

# Pick a bin dir: ~/.local/bin (created if needed), else the first writable
# dir already on PATH.
NAME="${DORK_LAUNCHER_NAME:-dork}"
TARGET=""
mkdir -p "$HOME/.local/bin" 2>/dev/null || true
for dir in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin "$HOME/bin"; do
  if [[ -d "$dir" && -w "$dir" ]]; then
    TARGET="$dir/$NAME"
    BIN_DIR="$dir"
    break
  fi
done
if [[ -z "$TARGET" ]]; then
  echo >&2 "[dork] No writable bin dir found (tried ~/.local/bin, /opt/homebrew/bin, /usr/local/bin, ~/bin)."
  exit 1
fi

if [[ -e "$TARGET" ]] && ! grep -q "generated by dork install" "$TARGET" 2>/dev/null; then
  echo >&2 "[dork] $TARGET already exists and wasn't created by this installer — refusing to overwrite."
  echo >&2 "[dork] Re-run with DORK_LAUNCHER_NAME=<other-name> to install under a different name."
  exit 1
fi

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# $NAME — generated by dork install; delegates to \$DORK_HOME/bin/dork.
export DORK_PROG="$NAME"
exec bash "$DORK_HOME/bin/dork" "\$@"
EOF
chmod +x "$TARGET"

echo "[dork] Installed $TARGET → $DORK_HOME/bin/dork"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "[dork] NOTE: $BIN_DIR is not on your PATH — add it to your shell profile:"
     echo "       export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac
echo "[dork] Try: $NAME flow    (and '$NAME init' inside a repo to set it up)"
